language: java
env:
  global:
  - secure: hNHWoqd0DuZXeaIymCjFDVXw7zuAr8on9yli9Kwr4Rw5Ga1FvZOa2noe1RjP0AC+b7S1vvR8ijbGOOn0bM9PfgfrfglqI/3rM/CkxkYOOvzJAbAzYjM9psFGR4RhhD3IaSomvXKRvRO39rIYXZH4/2+73tzbYRe24Xvb4KmYfV8=
  - secure: mqLzHvJZz12m7eHwqbDJW70WfcJ+9W9L15yFJjKhSmYZ6dHSUq11oLciRw+vW/rzSN0NUJeFu+IhHoC8JJPXk4SjB0ahZGc2EmI6tdE5Dr6HmgpnKuQl2X/WoCWu1S7vWYcCHb5pfVQ5Rh6Ue4m9XyBK9rr6zJziT4o2GMJTy5M=
cache:
  directories:
  - $HOME/.m2
install:
- mvn test -Dgpg.skip=true
after_success:
- openssl aes-256-cbc -K $encrypted_bfb8b049ccf7_key -iv $encrypted_bfb8b049ccf7_iv -in pubring.gpg.enc -out pubring.gpg -d
- openssl aes-256-cbc -K $encrypted_bfb8b049ccf7_key -iv $encrypted_bfb8b049ccf7_iv -in secring.gpg.enc -out secring.gpg -d
- mvn clean deploy --settings settings.xml -Dgpg.keyname=$GPG_KEYNAME -Dgpg.passphrase=$GPG_PASSPHRASE -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.defaultKeyring=false
notifications:
  slack:
    secure: n4Wjj39xafqRkhsBJZ003iA8WGOajCloRrf4z4t0OpEhlGZ8n6jCtiwq0+98sPJLU5mczhLkc46UBubB1ppdlngUQILt2N3AAvezrOGKUhxq5Sdl6XDSu/GW2Rhxo+18X/1A0ndkoYdLmFkTqm3Xgxo1qddgbIIH9lITqXz3dyo=
